name: Backup Repositories

on:
  schedule:
    - cron: "* * * * *"  # Run once daily at midnight

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Clone and Zip Repositories
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
          DEST_REPO: "destination"
        run: |
          curl -s -H "Authorization: token $GITHUBTOKEN" "https://api.github.com/users/dkbanra/repos?per_page=100" | jq -r '.[].clone_url' | while IFS= read -r REPO_URL; do
              REPO_NAME=$(basename -s .git "$REPO_URL")
              echo "Cloning $REPO_NAME..."
              git clone --depth 1 "$REPO_URL"
              echo "Zipping $REPO_NAME..."
              zip -r "$REPO_NAME.zip" "$REPO_NAME"
              echo "Moving $REPO_NAME.zip to destination repository..."
              cp "$REPO_NAME.zip" "$DEST_REPO"
              rm -rf "$REPO_NAME" "$REPO_NAME.zip"
              echo "Backup of $REPO_NAME completed."
          done
